### Numpy in python
Numpy is funadamental library for scientific computing in python.It provides support for arrays and matrices, along with collection of functions to operate on these data structures. 

In [1]:
import numpy as np

In [3]:
#create an array in np
#creating 1D array
arr = np.array([1,2,4,5,6])
print(arr)
print(type(arr))

#creating 2D array
arr1 = np.array([[2,4,5],[2,4,6],[1,67,8]])
print(arr1.shape)

[1 2 4 5 6]
<class 'numpy.ndarray'>
(3, 3)


In [4]:
#arange function - it allows you to create list having start,end,step parameter
#syntax - np.arange(start,end,step)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [5]:
#creating unit matrix (all 1's)
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
#creating identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
#attributes of Numpy
arr = np.array([[1,2,3,5],[34,56,21,52]])

print("Array:",arr)
print("Array shape:",arr.shape)
print("Array dimention:",arr.ndim)
print("Array size(num of elements):",arr.size)
print("Array Data type:",arr.dtype)
print("Array Item size(in bytes):",arr.itemsize)



Array: [[ 1  2  3  5]
 [34 56 21 52]]
Array shape: (2, 4)
Array dimention: 2
Array size(num of elements): 8
Array Data type: int32
Array Item size(in bytes): 4


In [8]:
# Numpy Vectorize Operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,22,1,3,4])

## Element wise addition
print("add",arr1 +arr2)

## Element wise subtraction
print("Sub",arr1-arr2)

## Element wise Multiplication
print("Mult",arr1*arr2)

## Element wise Division
print("Div",arr1/arr2)

add [ 4 24  4  7  9]
Sub [ -2 -20   2   1   1]
Mult [ 3 44  3 12 20]
Div [0.33333333 0.09090909 3.         1.33333333 1.25      ]


In [9]:
#universal function
arr = np.array([1,2,3,4,5])

#square root
print(np.sqrt(arr))

#exponential
print(np.exp(arr))

#sin
print(np.sin(arr))

#natural log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [10]:
# array slicing and indexing operation
arr = np.array([[1,3,5,65],[2,3,15,6],[2,55,76,7]])
arr

array([[ 1,  3,  5, 65],
       [ 2,  3, 15,  6],
       [ 2, 55, 76,  7]])

In [11]:
#accessing 15,6,76,7
#formula - arr[row_start:row_end, column_index] or arr[row_start:row_end, column_index:col_index]
#-ve column index starts from last
arr[2:,:-1]

array([[ 2, 55, 76]])

In [12]:
#modifying array
arr[0][0] = 100
print(arr)

[[100   3   5  65]
 [  2   3  15   6]
 [  2  55  76   7]]


In [23]:
arr[1:] = 500
print(arr)

[[100   3   5  65]
 [500 500 500 500]
 [500 500 500 500]]


In [25]:
#statastical concept--Normalization
#def --->to have mean 0 standard daviation of 1
data = np.array([1,2,3,4,5])
mean = np.mean(data)
std = np.std(data)

#normalize the data
noramalize_data = (data-mean) / std
print(f"Normalized data:{noramalize_data}")

Normalized data:[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [39]:
#logical operation
data1 = np.array([1,3,24,54,5,6])
# data1>5  #o/p = array([False, False, False,  True, False,  True])
data1[(data1>5) & (data1<50)]

array([24,  6])